site:
    baseUrl: https://theswiftdev.com/
    language: en-US
    title: The.Swift.Dev.
    description: Articles about application development using the Swift programming language.
    dateFormat: "yyyy/MM/dd"
    noindex: false

themes:
    use: "default"
    folder: "themes"
    templates:
        folder: "templates"
    assets:
        folder: "assets"
    overrides:
        folder: "theme_overrides"

types:
    folder: "types"

content:
    folder: "content"
    assets:
        folder: "assets"
